### ISSUE TITLE
Copper Powered Rails Crash

### ISSUE THREAD

**Issue by BioMasterZap** [FXCourel/Copper-Rails#5]
With v1.0.4 for Fabric 1.20.4, the mod seems to crash when the Copper Rails attempt to oxidize. Here is a gist to the crash report: https://gist.github.com/BioMasterZap/238d2d9c886e471e25ea15c2a7c03616

I previously encountered this crash when testing the rails with minecarts on them, but after testing with no other mods present except Fabric API, I got it crash when I wasn't interacting with the rail. I could provide the log if needed, but it is just loading the world, then "[Server thread/ERROR]: Encountered an unexpected exception" followed by the crash report a minute and half later.

**Comment by DevMC7** [comment]
It can't find the oxidization method in the code. Should be easy to fix

**Comment by EfficientStinkbug** [comment]
is this the same problem? 
Time: 2024-09-08 13:59:40
Description: Exception ticking world

java.lang.NoSuchMethodError: 'void net.robofox.copperrails.block.custom.OxidizableCopperRailBlock.method_33621(net.minecraft.class_2680, net.minecraft.class_3218, net.minecraft.class_2338, net.minecraft.class_5819)'
	at net.robofox.copperrails.block.custom.OxidizableCopperRailBlock.method_9514(OxidizableCopperRailBlock.java:20)
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:1207)
	at net.minecraft.class_3218.method_18203(class_3218.java:510)
	at net.minecraft.class_3215.method_14161(class_3215.java:379)
	at net.minecraft.class_3215.method_12127(class_3215.java:324)
	at net.minecraft.class_3218.method_18765(class_3218.java:341)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:948)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:845)
	at net.minecraft.class_1132.method_3748(class_1132.java:110)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by DevMC7** [comment]
yeah

**Comment by FXCourel** [comment]
Sorry to answer so late. I forgot to mention in new uploads that 1.20 version is only for 1.20 and 1.20.1. Oxydation code changed in later 1.20.x version and this would need an other version of the mod. Maintaining for 1.18.x, 1.20, 1.21.x is already a bit a mess to manage, I don't have the time to make a specific version for later 1.20.x versions.
